import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Box from '@mui/material/Box'
import Paper from '@mui/material/Paper'
import Tab from '@mui/material/Tab'
import Tabs from '@mui/material/Tabs'
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined'
import SendIcon from '@mui/icons-material/Send'
import SyncIcon from '@mui/icons-material/Sync'
import TaskIcon from '@mui/icons-material/Task'
import RawOodiReports from '@client/components/ReportsPage/OodiReports/RawOodiReports'
import OodiReports from '@client/components/ReportsPage/OodiReports/OodiReports'
import SisReports from '@client/components/ReportsPage/SisReports'
import EnrolmentLimbo from '@client/components/ReportsPage/EnrolmentLimbo'
import UnsentEntries from '@client/components/ReportsPage/UnsentEntries'
import { getAllOodiReportsAction, getUsersOodiReportsAction } from '@client/utils/redux/oodiReportsReducer'
import { resetFiltersAction } from '@client/utils/redux/sisReportsReducer'

export default () => {
  const [activeTab, setActiveTab] = useState(0)
  const [initialLoad, setInitialLoad] = useState(true)
  const dispatch = useDispatch()
  const user = useSelector((state) => state.user.data)
  const reports = useSelector((state) => state.oodiReports)
  const { mooc, unsentBatchCount } = useSelector((state) => state.sisReports)
  const oodiEnabled = false

  useEffect(() => {
    if (!user.adminMode && oodiEnabled) dispatch(getUsersOodiReportsAction(user.id))
  }, [user, dispatch])

  useEffect(() => {
    // If batch in url is a mooc report, switch
    // to correct tab, only once
    if (mooc && initialLoad) {
      setActiveTab(1)
      setInitialLoad(false)
    }
  }, [mooc, initialLoad])

  const handleTabChange = (_, activeIndex) => {
    // Fetch old reports only if tab is opened
    dispatch(resetFiltersAction())
    setActiveTab(activeIndex)
    if (user.adminMode && activeIndex > 2 && !reports.data.length && oodiEnabled) dispatch(getAllOodiReportsAction())
  }

  let panes = [
    {
      key: 'manual',
      dataCy: 'sis-reports-tab',
      label: 'SIS Reports',
      render: () => <SisReports />
    }
  ]

  if (user.adminMode) {
    panes = [
      ...panes,
      {
        key: 'mooc',
        dataCy: 'sis-auto-reports-tab',
        label: 'SIS Autogenerated Reports',
        render: () => <SisReports mooc />
      },
      {
        key: 'limbo',
        dataCy: 'sis-limbo',
        label: 'Enrolment limbo',
        icon: <SyncIcon />,
        render: () => <EnrolmentLimbo />
      },
      {
        key: 'unsent',
        dataCy: 'sis-unsent-entries',
        label: 'Unsent entries',
        icon: <SendIcon />,
        badge: unsentBatchCount,
        render: () => <UnsentEntries />
      }
    ]
  }

  if (oodiEnabled) {
    if (!user.adminMode) {
      panes = [
        ...panes,
        {
          key: 'pretty',
          dataCy: 'pretty-oodi-reports-tab',
          label: 'OODI Reports',
          icon: <TaskIcon />,
          render: () => <OodiReports />
        }
      ]
    }

    if (user.adminMode) {
      panes = [
        ...panes,
        {
          key: 'pretty',
          dataCy: 'pretty-oodi-reports-tab',
          label: 'Pretty (OODI)',
          icon: <TaskIcon />,
          render: () => <OodiReports />
        },
        {
          key: 'raw',
          dataCy: 'raw-oodi-reports-tab',
          label: 'Raw (OODI)',
          icon: <DescriptionOutlinedIcon />,
          render: () => (
            <RawOodiReports
              reports={{
                ...reports,
                data: reports.data.filter((report) => report.reporterId)
              }}
            />
          )
        },
        {
          key: 'mooc-old',
          dataCy: 'oodi-mooc-reports-tab',
          label: 'Autogenerated MOOC (OODI)',
          icon: <DescriptionOutlinedIcon />,
          render: () => (
            <RawOodiReports
              reports={{
                ...reports,
                data: reports.data.filter((report) => !report.reporterId)
              }}
            />
          )
        }
      ]
    }
  }

  const activePane = panes[activeTab] || panes[0]

  return (
    <Paper variant="outlined">
      <Tabs value={activeTab} onChange={handleTabChange}>
        {panes.map((pane) => (
          <Tab
            key={pane.key}
            data-cy={pane.dataCy}
            icon={pane.icon}
            iconPosition="start"
            label={
              pane.badge ? (
                <Box sx={{ display: 'flex', alignItems: 'center' }}>
                  {pane.label}
                  <Box
                    component="span"
                    sx={{
                      ml: '0.6em',
                      px: '0.65em',
                      py: '0.5em',
                      minWidth: '2em',
                      borderRadius: '500rem',
                      backgroundColor: '#db2828',
                      color: '#fff',
                      fontSize: '0.8rem',
                      fontWeight: 700,
                      lineHeight: 1
                    }}
                  >
                    {pane.badge}
                  </Box>
                </Box>
              ) : (
                pane.label
              )
            }
          />
        ))}
      </Tabs>
      <Box sx={{ p: 2 }}>{activePane.render()}</Box>
    </Paper>
  )
}
